site_url: https://landing.docparsley.com
display_url: https://landing.docparsley.com
logo_url: https://landing.docparsley.com/img/login-logo.png
show_preview_links: false
backend:
  name: git-gateway
  repo: Kristopher-Ray/docparsley-landing-brentpella
  branch: master
# This line should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under images/uploads
public_folder: "/img"
collections:
  - name: "promotions"
    label: "Landing Pages"
    folder: "content/promotions"
    media_folder: '/static/img/'
    public_folder: '/img/'
    filter: {field: "visible", value: true}
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Visible in CMS", name: "visible", widget: hidden, default: true}
      - {label: "Draft", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "Hidden Reference Title (Backend)", name: "title", widget: "string"}
      - {label: "Name for Attribution", name: "attribution", widget: "string"}
      - {label: "Meta (Page) Title", name: "metaTitle", widget: "string"}
      - {label: "Meta Description", name: "description", widget: "string", required: false}
      - {label: "Banner Title", name: "banner_title", widget: "string"}
      - {label: "Banner Tagline", name: "banner_tagline", widget: "string"}
      - {label: "Banner Body", name: "banner_text", widget: "text"}
      - {label: "Banner Image", name: "banner_image", widget: "image" }
      - {label: "Banner Image Position Override", name: "bannerimgposition", widget: "string", required: false}
      - {label: "Banner Button Left", name: "cta_button_left", widget: "text"}
      - {label: "Banner Button Right", name: "cta_button_right", widget: "text"}
      - {label: "Product Image", name: "cta_image", widget: "image" }
      - {label: "Quote", name: "quote", widget: "text"}
      - {label: "Section Image", name: "sectionimage", widget: "image" }
      - {label: "What I know Section", name: "body", widget: "markdown", required: false}
      - {label: "Slug (eg. landing trailing URL)", name: "slug", widget: "string"}
      - {label: "Exit Popup Content", name: "exitCTA", widget: "text"}
      - {label: "klaviyo class", name: "klaviyo", widget: "string"}
  - name: "logos"
    label: "Logo Carousel"
    folder: "content/logos"
    media_folder: '/static/img/logos'
    public_folder: '/img/logos'
    filter: {field: "visible", value: true}
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Visible in CMS", name: "visible", widget: hidden, default: true}
      - {label: "Logo Name / Title / Alt Tag", name: "title", widget: "string"}
      - {label: "Logo Image", name: "image", widget: "image" }
      - {label: "Order", name: "weight", widget: "number" }
  - name: "products"
    label: "Featured Products"
    folder: "content/products"
    media_folder: '/static/img/products'
    public_folder: '/img/logos'
    filter: {field: "visible", value: true}
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Visible in CMS", name: "visible", widget: hidden, default: true}
      - {label: "Product Name", name: "title", widget: "string"}
      - {label: "Original Price", name: "price", widget: "string" }
      - {label: "Sale Price", name: "sale_price", widget: "string" }
      - {label: "Link", name: "outbound", widget: "string" }
      - {label: "Image", name: "image", widget: "image" }
      - {label: "Order", name: "weight", widget: "number" }
  - name: "testimonials"
    label: "Testimonials"
    folder: "content/testimonials"
    media_folder: '/static/img'
    public_folder: '/img'
    filter: {field: "visible", value: true}
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Visible in CMS", name: "visible", widget: hidden, default: true}
      - {label: "Attribution Name", name: "title", widget: "string"}
      - {label: "stars", name: "stars", widget: "number", min: 1, max: 5, default: 5 }
      - {label: "Order", name: "weight", widget: "number" }
      - {label: "Testimonial", name: "body", widget: "markdown"}
  - name: "home_sections"
    label: "Repeating Sections"
    folder: "content/home_sections"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Reference Title (hidden)", name: "title", widget: "string"}
      - {label: "Section Content", name: "body", widget: "markdown"}
      - {label: "Background Image", name: "image", widget: "image" }
      - {label: "Order", name: "weight", widget: "number" }